// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineCodePlatform.DAL;

namespace OnlineCodePlatform.Migrations
{
    [DbContext(typeof(OnlineCodeContext))]
    partial class OnlineCodeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineCodePlatform.Models.ProblemSolution", b =>
                {
                    b.Property<int>("ProblemSolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProblemSolutionId");

                    b.ToTable("ProblemSolution");
                });

            modelBuilder.Entity("OnlineCodePlatform.Models.ProblemStatement", b =>
                {
                    b.Property<int>("ProblemStatementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProblemSolutionId")
                        .HasColumnType("int");

                    b.HasKey("ProblemStatementId");

                    b.HasIndex("ProblemSolutionId")
                        .IsUnique();

                    b.ToTable("ProblemStatements");
                });

            modelBuilder.Entity("OnlineCodePlatform.Models.ProblemStatement", b =>
                {
                    b.HasOne("OnlineCodePlatform.Models.ProblemSolution", "ProblemSolution")
                        .WithOne("ProblemStatement")
                        .HasForeignKey("OnlineCodePlatform.Models.ProblemStatement", "ProblemSolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemSolution");
                });

            modelBuilder.Entity("OnlineCodePlatform.Models.ProblemSolution", b =>
                {
                    b.Navigation("ProblemStatement");
                });
#pragma warning restore 612, 618
        }
    }
}
